package com.suryoday.payment.payment;

import org.json.JSONObject;

public class ReadLineByLineExample1 {

	public static void main(String[] args) {
		String breResponse = "{\r\n" + "    \"BUREAU_POLICY_CREDIT_ENQUIRY_TW\": {\r\n"
				+ "        \"result\": true,\r\n" + "        \"deviation_group\": null,\r\n"
				+ "        \"derived_values\": {\r\n" + "            \"CR_OBJ\": {\r\n"
				+ "                \"currentapplication\": {\r\n"
				+ "                    \"Current_Application_Details\": {\r\n"
				+ "                        \"currentapplicantdetails\": {\r\n"
				+ "                            \"firstname\": \"NARESH\",\r\n"
				+ "                            \"gendercode\": 1,\r\n"
				+ "                            \"telephoneextension\": \"\",\r\n"
				+ "                            \"emailid\": null,\r\n"
				+ "                            \"lastname\": \"TUSHAR DHINGRA\",\r\n"
				+ "                            \"incometaxpan\": \"CCUPU1429K\",\r\n"
				+ "                            \"mobilephonenumber\": \"6995615873\",\r\n"
				+ "                            \"middlename2\": \"\",\r\n"
				+ "                            \"middlename3\": \"\",\r\n"
				+ "                            \"middlename1\": \"\",\r\n"
				+ "                            \"telephonenumberapplicant1st\": \"\",\r\n"
				+ "                            \"telephonetype\": \"\",\r\n"
				+ "                            \"dateofbirthapplicant\": \"19840502\"\r\n"
				+ "                        },\r\n" + "                        \"amountfinanced\": \"\",\r\n"
				+ "                        \"financepurpose\": \"\",\r\n"
				+ "                        \"currentotherdetails\": {\r\n"
				+ "                            \"income\": \"\",\r\n"
				+ "                            \"timewithemployer\": \"\",\r\n"
				+ "                            \"employmentstatus\": \"\",\r\n"
				+ "                            \"maritalstatus\": \"\",\r\n"
				+ "                            \"numberofmajorcreditcardheld\": \"\"\r\n"
				+ "                        },\r\n" + "                        \"durationofagreement\": \"\",\r\n"
				+ "                        \"enquiryreason\": \"\",\r\n"
				+ "                        \"currentapplicantaddressdetails\": {\r\n"
				+ "                            \"country\": \"India\",\r\n"
				+ "                            \"pincode\": \"401209\",\r\n"
				+ "                            \"city\": \"Mumbai\",\r\n"
				+ "                            \"bldgnosocietyname\": \"\",\r\n"
				+ "                            \"State\": \"27\",\r\n"
				+ "                            \"flatnoplotnohouseno\": \"301/ SWANAND TANIA TOWN, ALKAPURI ROAD,\",\r\n"
				+ "                            \"landmark\": \"\",\r\n"
				+ "                            \"roadnonamearealocality\": \"301/ SWANAND TANIA TOWN, ALKAPURI ROAD,\"\r\n"
				+ "                        }\r\n" + "                    }\r\n" + "                },\r\n"
				+ "                \"creditprofileheader\": {\r\n" + "                    \"subscribername\": \"\",\r\n"
				+ "                    \"subscriber\": \"\",\r\n" + "                    \"subscribe\": \"\",\r\n"
				+ "                    \"reportdate\": \"20231122\",\r\n"
				+ "                    \"reportnumber\": \"002159519969\",\r\n"
				+ "                    \"version\": \"12\",\r\n"
				+ "                    \"reporttime\": \"20231122\",\r\n"
				+ "                    \"enquiryusername\": \"\"\r\n" + "                },\r\n"
				+ "                \"SCORE\": {\r\n" + "                    \"BureauScore\": \"171\",\r\n"
				+ "                    \"bureauscoreconfidlevel\": \"\"\r\n" + "                },\r\n"
				+ "                \"usermessagetext\": \"\",\r\n" + "                \"Header\": \"\",\r\n"
				+ "                \"CAISAccount\": {\r\n" + "                    \"CAISAccountDETAILS\": [],\r\n"
				+ "                    \"caissummary\": \"\"\r\n" + "                },\r\n"
				+ "                \"NonCreditCAPS\": \"\",\r\n" + "                \"TotalCAPSSummary\": \"\",\r\n"
				+ "                \"CAPS\": {\r\n" + "                    \"CAPSApplicationDetails\": [],\r\n"
				+ "                    \"CAPSSummary\": \"\"\r\n" + "                },\r\n"
				+ "                \"exactmatch\": \"\"\r\n" + "            },\r\n"
				+ "            \"COUNT_ENQUIRY_IN_LAST_THREE_MONTHS\": 0\r\n" + "        },\r\n"
				+ "        \"description\": \"Checks whether the number of recent credit inquiries is within an acceptable limit.\",\r\n"
				+ "        \"definition\": null,\r\n" + "        \"deviation\": false\r\n" + "    },\r\n"
				+ "    \"MAX_LOAN_AMOUNT\": {\r\n" + "        \"result\": true,\r\n"
				+ "        \"deviation_group\": null,\r\n" + "        \"derived_values\": {},\r\n"
				+ "        \"description\": \"Maximum loan allowed is 150000\",\r\n"
				+ "        \"definition\": null,\r\n" + "        \"deviation\": false\r\n" + "    },\r\n"
				+ "    \"MIN_LOAN_AMOUNT\": {\r\n" + "        \"result\": true,\r\n"
				+ "        \"deviation_group\": null,\r\n" + "        \"derived_values\": {},\r\n"
				+ "        \"description\": \"Minimum loan amount allowed is 15000.\",\r\n"
				+ "        \"definition\": null,\r\n" + "        \"deviation\": false\r\n" + "    },\r\n"
				+ "    \"AGE_CHECK\": {\r\n" + "        \"result\": true,\r\n"
				+ "        \"deviation_group\": \"Level 1\",\r\n" + "        \"derived_values\": {},\r\n"
				+ "        \"description\": \"The age of the applicant must at least be 21 if the current loan doesn't already exist in the database. Deviated if applicant age not as per policy norms\",\r\n"
				+ "        \"definition\": null,\r\n" + "        \"deviation\": false\r\n" + "    },\r\n"
				+ "    \"MAX_AGE\": {\r\n" + "        \"result\": true,\r\n" + "        \"deviation_group\": null,\r\n"
				+ "        \"derived_values\": {},\r\n"
				+ "        \"description\": \"Maximum age of the applicant should not exceed 60.\",\r\n"
				+ "        \"definition\": null,\r\n" + "        \"deviation\": false\r\n" + "    },\r\n"
				+ "    \"BUREAU_POLICY_DEFAULT_ACCOUNTS\": {\r\n" + "        \"result\": true,\r\n"
				+ "        \"deviation_group\": \"Level 1\",\r\n" + "        \"derived_values\": {\r\n"
				+ "            \"NUM_SPECIAL_MENTION_ACCOUNTS_LAST_24_MONTHS\": 0,\r\n"
				+ "            \"NUM_SUIT_FILED_ACCOUNTS_LAST_24_MONTHS\": 0,\r\n"
				+ "            \"NUM_SETTLED_ACCOUNTS_LAST_24_MONTHS\": 0,\r\n"
				+ "            \"NUM_RESTRUCTURED_ACCOUNTS\": 0,\r\n"
				+ "            \"NUM_WRITTEN_OFF_ACCOUNTS_LAST_24_MONTHS\": 0,\r\n"
				+ "            \"COUNT_WILLFUL_DEAFULT_ACCOUNTS\": 0\r\n" + "        },\r\n"
				+ "        \"description\": \"Checks if several financial parameters related to the applicant's credit history are equal to zero.\",\r\n"
				+ "        \"definition\": \"Verifies the following criteria for the applicant's credit history in the last 24 months:  1) No suits filed accounts 2)No restructured accounts 3)No special mention accounts 4)No willful default accounts 5)No written-off accounts 6)No settled accounts. GO if all the conditions are met, else NOGO\",\r\n"
				+ "        \"deviation\": false\r\n" + "    },\r\n" + "    \"30_PLUS_DPD_CHECK_TW\": {\r\n"
				+ "        \"result\": true,\r\n" + "        \"deviation_group\": \"Level 1\",\r\n"
				+ "        \"derived_values\": {\r\n" + "            \"COUNT_30_PLUS_DPD_CHECK\": []\r\n"
				+ "        },\r\n"
				+ "        \"description\": \"GO if the count of 30 plus DPD is 0 otherwise NOGO. Deviated if credit bureau - DPD greater than 30 in an Active Tradeline in past 12 months\",\r\n"
				+ "        \"definition\": \"\",\r\n" + "        \"deviation\": false\r\n" + "    },\r\n"
				+ "    \"60_PLUS_DPD_CHECK_TW\": {\r\n" + "        \"result\": true,\r\n"
				+ "        \"deviation_group\": \"Level 1\",\r\n" + "        \"derived_values\": {\r\n"
				+ "            \"COUNT_60_PLUS_DPD_CHECK\": []\r\n" + "        },\r\n"
				+ "        \"description\": \"GO if the count of 60 plus DPD in the last 24 months is 0, else NOGO. Deviated if credit bureau - DPD greater than 60 in an Active Tradeline in past 12 months\",\r\n"
				+ "        \"definition\": \"\",\r\n" + "        \"deviation\": false\r\n" + "    },\r\n"
				+ "    \"NAME_MATCH\": {\r\n" + "        \"result\": false,\r\n"
				+ "        \"deviation_group\": \"Level 1\",\r\n" + "        \"derived_values\": {\r\n"
				+ "            \"NAME_MATCH_VALUE\": 70\r\n" + "        },\r\n"
				+ "        \"description\": \"Approval is given if the system has the name match. Deviated if there is name mismatch between KYC document\",\r\n"
				+ "        \"definition\": null,\r\n" + "        \"deviation\": false\r\n" + "    },\r\n"
				+ "    \"BUREAU_SCORE_SSFB_TW_BRE_021\": {\r\n" + "        \"result\": true,\r\n"
				+ "        \"deviation_group\": \"Level 1\",\r\n" + "        \"derived_values\": {},\r\n"
				+ "        \"description\": \"Approved if the credit score falls within the range. Deviated if credit bureau score is less than acceptable norms\",\r\n"
				+ "        \"definition\": \"\",\r\n" + "        \"deviation\": false\r\n" + "    },\r\n"
				+ "    \"NEGATIVE_LOCALITY\": {\r\n" + "        \"result\": true,\r\n"
				+ "        \"deviation_group\": \"Level 2\",\r\n" + "        \"derived_values\": {},\r\n"
				+ "        \"description\": \"Checks if the address type is \\\"Current Residence\\\" and if the locality is marked as negative. Deviated if FI result is Negative\",\r\n"
				+ "        \"definition\": null,\r\n" + "        \"deviation\": false\r\n" + "    },\r\n"
				+ "    \"MIN_AGE\": {\r\n" + "        \"result\": true,\r\n" + "        \"deviation_group\": null,\r\n"
				+ "        \"derived_values\": {},\r\n"
				+ "        \"description\": \"Minimum age of the applicant must be 21 or more.\",\r\n"
				+ "        \"definition\": null,\r\n" + "        \"deviation\": false\r\n" + "    },\r\n"
				+ "    \"0_PLUS_DPD_CHECK_TW\": {\r\n" + "        \"result\": true,\r\n"
				+ "        \"deviation_group\": \"Level 1\",\r\n" + "        \"derived_values\": {\r\n"
				+ "            \"COUNT_0_PLUS_DPD_CHECK\": []\r\n" + "        },\r\n"
				+ "        \"description\": \"If count of 0 plus DPD in the last 3 months is 0, then GO otherwise NOGO. Deviated if Credit Bureau - DPD is greater than 0 in an Active Tradeline in the past 3 months\",\r\n"
				+ "        \"definition\": \"\",\r\n" + "        \"deviation\": false\r\n" + "    }\r\n" + "}";
		JSONObject breResponseJson = new JSONObject(breResponse);
		int count = 1;
		for (String keys : breResponseJson.keySet()) {
			if (!breResponseJson.getJSONObject(keys).get("deviation_group").equals(null)) {
				String p = breResponseJson.getJSONObject(keys).get("deviation_group").toString();
				int a = Character.getNumericValue(p.charAt(6));
				if (a > count) {
					count = a;
				}
			}
		}
		System.out.println("Level " + count);
	}
}
