package com.suryoday.roaocpv.serviceImpl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.suryoday.aocpv.pojo.AocpvLoanCreation;
import com.suryoday.aocpv.service.AocpvLoanCreationService;
import com.suryoday.roaocpv.others.ROAOCPVGenerateProperty;
import com.suryoday.roaocpv.service.LoanAgreementService;

@Service
public class LoanAgreementServiceImpl implements LoanAgreementService{

	@Autowired
	AocpvLoanCreationService aocpvLoanCreationService;
	
	@Override
	public String reportPdf(StringBuilder htmlString, long applicationNoInLong) {
		ROAOCPVGenerateProperty x=ROAOCPVGenerateProperty.getInstance();
        x.getappprop();
		
		AocpvLoanCreation aocpvLoanCreation = aocpvLoanCreationService.findByApplicationNo(applicationNoInLong);
			
		htmlString.append(new String("<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "    <head>\r\n"
				+ "        <style>\r\n"
				+ "          table,\r\n"
				+ "    th,\r\n"
				+ "    td {\r\n"
				+ "      border: 1px solid black;\r\n"
				+ "      border-collapse: collapse;\r\n"
				+ "    }\r\n"
				+ "        </style>\r\n"
				+ "      </head>\r\n"
				+ "    <body>\r\n"
				+ "        <div class=\"logo\" style=\"text-align: right;\">\r\n"
				+ "            <img style=\"width: 20%;\" src=\""+x.LOGO+"logo.jpg\">\r\n"
				+ "          </div>\r\n"
				+ "        <div class=\"container\">\r\n"
				+ "        <h3 style=\"text-align: center;\">TERMS AND CONDITIONS OF LOAN</h3>\r\n"
				+ "            <p> 1) Loan amount should be utilized for income generating purpose mentioned to SSFB.</p>\r\n"
				+ "            <p> 2) Borrower has to maintain sufficient balance in the bank accounts and if the borrower fails to honor the payments and or SI has failed at two or more\r\n"
				+ "                successive occasion, Bank shall visit place of residence or work for recovery of dues. </p>\r\n"
				+ "            <p> 3) I authorize the Bank to debit my Savings /Current accounts maintained with Suryoday Small finance Bank Ltd for the payment of EMIs as pe the Standing Instruction\r\n"
				+ "                (SI) Provided</p> \r\n"
				+ "            <p> 4) In case of non-availability of funds in my Savings /Current accounts maintained with Suryoday Small finance Bank Ltd, bank will have the right to file a case under\r\n"
				+ "                section 25 of Payment and Settlement System Act 2007</p>  \r\n"
				+ "            <p> 5) Due to insufficient balance if the Standing Instruction (SI) provided by the borrower fails, he/she would be liable to pay charges towards each Standing\r\n"
				+ "                Instruction (SI) bounced.</p> \r\n"
				+ "            <p> 6) Borrower has to pay cash handling charges for cash collection done by the bank staff towards installment collection</p>\r\n"
				+ "            <p> 7) The borrower’s information will be kept confidential and the same will not be shared with anybody except agencies approved by regulator/Government Authorities\r\n"
				+ "                and as per the policy of the Bank.</p>\r\n"
				+ "            <p> 8) Borrower has to repay the loan in monthly installments with an effective interest rate on diminishing balance as mentioned in Sanction Letter</p>\r\n"
				+ "            <p> 9) The Sanction Letter discloses the rate of interest, *Loan Processing Fee (as applicable for loans more than 25,000/-), insurance premium and all other terms and\r\n"
				+ "                conditions in clear and transparent manner.</p>\r\n"
				+ "            <p> 10) The interest and other charges may vary depending on the loan amount, tenure & frequency chosen by the borrower, which shall be as mentioned in the Sanction\r\n"
				+ "                Letter.</p>\r\n"
				+ "            <p> 11) Bank shall provide every borrower, a copy of Sanction Letter, Key fact sheet, terms and conditions of the loan and a passbook/loan card/repayment schedule\r\n"
				+ "                which has exact due date of repayment of loan, frequency of loan, break up of principal and interest for the loans disbursed.</p> \r\n"
				+ "            <p> 12) The Bank in compliance of regulatory instruction from RBI is under the obligation to declare all loan account of a borrower as NPA, even in case one loan is NPA\r\n"
				+ "                and other are regularly paid, i.e., NPA classification is at borrower wise instead of loan wise. </p>\r\n"
				+ "            <p> 13) The Borrower shall authorize the Bank /Agent / RBI and its officer / staff / Auditor to visit / inspect the workplace / residence / business / property / product\r\n"
				+ "                financed during the working hours subject to advance intimation and further authorize to seek information and documents, as may be required.</p> \r\n"
				+ "            <p> 14) In case of difference in the details of the address mentioned in Officially Valid Document (OVD,) Borrower shall provide deemed OVD followed by corrected OVD\r\n"
				+ "                or e-kyc/ Aadhaar Biometric Authentication and if the Borrower fails to comply, the Bank is authorized to take such action it may deem fit.</p>\r\n"
				+ "            <p> 15) The Borrower confirms and authorizes the Bank to send digital loan documents through an SMS link on the registered mobile number of the Borrower instead of\r\n"
				+ "                physical print copy if digital means is available. The Borrower further understands and confirms that the above will be shared by Bank on the mobile number\r\n"
				+ "                provided by the Borrower to the Bank and additionally, the Borrower can approach the Bank to obtain the same. </p>   \r\n"
				+ "            <p> 16) The Borrower confirms that Bank/ has explained clearly in language the Borrower understands about the provision and norms with regards to RBI Guidelines on\r\n"
				+ "                Special Mention Account (SMA) and Non-Performing Asset (NPA). The Borrower further understands and confirms that the Borrower’s account will be classified\r\n"
				+ "                as below by the Bank depending on the delay in repayment from designated date:\r\n"
				+ "                <p style=\"padding-left: 50px;\">SMA-0 (upto 30 days);</p>\r\n"
				+ "                <p style=\"padding-left: 50px;\">SMA-1 (More than 30 days and upto 60 days); or</p>\r\n"
				+ "                <p style=\"padding-left: 50px;\">SMA-2(More than 60 days and upto 90 days); or</p>\r\n"
				+ "                <p style=\"padding-left: 50px;\">NPA (Above 90 days). </p></p>\r\n"
				+ "            <p> 17) The Borrower understands and confirms that Bank has made the Borrower understand the details of loan such as exact repayment date & amount of loan\r\n"
				+ "                instalment, frequency of repayment, breakup of Principal & interest shall be clearly mentioned in Key factsheet & detail repayment schedule.\r\n"
				+ "                </p>\r\n"
				+ "            <p> 18) Bank staff is adequately trained, and reasonable care is taken to prevent any inappropriate behavior wherein Bank will be accountable for the same.</p>\r\n"
				+ "            <p> 19) The Borrower if satisfied and wishes to avail Credit Shield Insurance for self and spouse and shall needs to pay the applicable premium towards Credit Shield\r\n"
				+ "                Insurance Premium to the master policy holder as mentioned in the Sanction Letter.</p> \r\n"
				+ "            <p> 20) The Bank is authorized to use outsource recovery agents for recovery.</p>\r\n"
				+ "            <p> 21) There is no penalty for prepayment of loans.</p>\r\n"
				+ "            <p> 22) The Bank does not take any type of asset as collateral/ security deposit/ margin money against any loan under microfinance.</p>\r\n"
				+ "            <p> 23) The Bank reserves the right to recalling the loan / accelerating payment of the outstanding loan amount anytime from the Borrower in case the Borrower\r\n"
				+ "                breaches any of the terms and conditions as mentioned herein.</p>\r\n"
				+ "            <p> 24) The Bank reserves the right at its sole discretion without assigning any reason whatsoever, to modify, vary or add to the terms and conditions, or to terminate the\r\n"
				+ "                said credit facility as may be sanctioned, at any time, and to recall any and/ or all the amounts due under the said loan without any notice or assigning any reason(s)\r\n"
				+ "                whatsoever. All amounts due in respect of the said credit facilities shall become payable forthwith on such demand.</p>\r\n"
				+ "            <p> 25) Except for the loan installments as mentioned in the Loan Card/Repayment Schedule, Borrower need not pay any amount in cash or kind to Bank staff or any\r\n"
				+ "                other person authorized by the Bank. </p>\r\n"
				+ "            <p> 26) Bank will acknowledge loan repayment by intimation through a short service message (SMS) to the registered mobile of the borrower. In case of any loss or nondelivery of SMS, the Borrower shall be solely responsible and in no event shall Bank be held liable or responsible for the same.</p> \r\n"
				+ "            <p> 27) All changes in the interest rates and charges of Loans will be only prospective and same will be informed to the borrower. </p>\r\n"
				+ "            <p> 28) The Bank is committed to fair and transparent lending practices.</p>\r\n"
				+ "            <p> 29) In case of any complaint/ grievance including recovery related grievance, Borrower can approach below mentioned grievance redressal mechanism established by\r\n"
				+ "                the Bank between 9:30 AM to 6:00 PM (2nd and 4th Saturday Holiday and public holidays)</p>   \r\n"
				+ "            <table style=\"width: 90%;\">\r\n"
				+ "            <tr>\r\n"
				+ "                <td style=\"font-weight: bold;\">Escalation Level</td>\r\n"
				+ "                <td style=\"font-weight: bold;\">Responsible </td>\r\n"
				+ "                <td style=\"font-weight: bold;\">Contact details</td>\r\n"
				+ "            </tr> \r\n"
				+ "            <tr>\r\n"
				+ "                <td> Level 1 </td>\r\n"
				+ "                <td> Smile center</td>\r\n"
				+ "                <td> ➢ Call us on 18001020210 (24*7 Toll free number).\r\n"
				+ "                    <p>➢ Write to us on smile@suryodaybank.com</p></td>\r\n"
				+ "            </tr>\r\n"
				+ "            <tr>\r\n"
				+ "                <td> Level 2 </td>\r\n"
				+ "                <td> Nodal Officer</td>\r\n"
				+ "                <td> Email ID: <a href=\"nodalofficer@suryodaybank.com\" style=\"text-decoration: none; color: #00788a\">nodalofficer@suryodaybank.com</a>, Landline Number: 022-40941556\r\n"
				+ "                    <p>Address: 1101, Sharda Terraces, Plot No.65, Sector 11, CBD Belapur, Navi Mumbai – 400614</p></td>\r\n"
				+ "            </tr>\r\n"
				+ "            <tr>\r\n"
				+ "                <td> Level 3 </td>\r\n"
				+ "                <td> Principal Nodal Officer</td>\r\n"
				+ "                <td> Email ID: <a href=\"pno@suryodaybank.com\" style=\"text-decoration: none; color: #00788a\">pno@suryodaybank.com</a>, Landline Number: 022-40941555\r\n"
				+ "                    <p>Address: 1101, Sharda Terraces, Plot No.65, Sector 11, CBD Belapur, Navi Mumbai – 400614</p></td>\r\n"
				+ "            </tr>\r\n"
				+ "            <tr>\r\n"
				+ "                <th colspan=\"3\">If still not satisfied with resolution provided and /or in case have not received a satisfactory response within 30 days, you may refer the case to the Banking\r\n"
				+ "                    Ombudsman.</th>\r\n"
				+ "            </tr>\r\n"
				+ "        </table>\r\n"
				+ "        <p> 30) Borrower hereby gives the rights to Suryoday Small Finance Bank Ltd to raise debt/loan in the form of shares/book debts by keeping the loan as security or\r\n"
				+ "            to Sell/Assign/Securitize the loan to Banks/Financial Institutions/SPVs and sharing borrower data/information with them for the said purpose. 7. In case of\r\n"
				+ "            overdue, bank has the right to deduct the amount from your saving account balance.</p>\r\n"
				+ "        <p> 31) In case the debt/loan/assignment/securitization is transferred to any Banks/Financial Institutions/SPVs, borrower agrees to repay the money on written\r\n"
				+ "            instructions from Suryoday Small Finance Bank Ltd to the said entity. </p>\r\n"
				+ "        <p> 32) Loan pre-closure of loans will be done at the Suryoday branches only.</p>\r\n"
				+ "        <p> 33) Additional moratorium charges will be collected at the time of disbursement based on number of days and the loan interest rate. </p>\r\n"
				+ "        <p> 34) In event of non-payment of an EMI by the borrower, bank will have right to file a case.</p> \r\n"
				+ "        <p> 35) Borrow hereby give rights to Suryoday Small Finance Bank to perform Credit Bureau check for the principal borrower and guarantor for this loan before the\r\n"
				+ "            loan and during the life of this loan.</p> \r\n"
				+ "        <p> 36) This Loan document shall be governed and construed in accordance with the substantive laws of India</p>\r\n"
				+ "        <p> 37) All disputes, differences and/ or claims arising out of this Loan document or Loan, whether during its subsistence or thereafter, shall be settled by arbitration in\r\n"
				+ "            accordance with the provisions of the Arbitration & Conciliation Act, 1996 (as amended from to time) or any other statutory modification or re-enactment thereof\r\n"
				+ "            for the time being in force (the “Arbitration Act”). The language of the arbitration proceedings shall be English. The parties agree that such arbitration proceedings\r\n"
				+ "            shall be conducted in Mumbai and the courts at Mumbai shall have exclusive jurisdiction.</p>    \r\n"
				+ "        <p> 38) Such arbitration shall be conducted by a sole arbitrator, appointed with the consent of both the parties to this Loan document in compliance of the Arbitration\r\n"
				+ "            Act. In the event of disagreement between the parties for such appointment or in the event one of the parties fails to give its consent to appoint the sole arbitrator,\r\n"
				+ "            the appointment shall be done in the manner provided in the Arbitration Act. It is expressly agreed that Arbitration process shall be conducted by fast track\r\n"
				+ "            procedure as specified in sub-section (3) of the section 29 B of the Arbitration and Conciliation Act 1996 (as amended from time to time).</p>\r\n"
				+ "            <p> 39) The arbitrator shall make a reasoned award (“Award”) and any Award made in the arbitration proceedings conducted/held pursuant to this clause shall be final\r\n"
				+ "            and binding. In the event of incapacity or resignation or death of the sole arbitrator so appointed, another arbitrator shall be appointed in the manner provided\r\n"
				+ "            in the Arbitration Act and such arbitrator so appointed shall be entitled to proceed with the reference from the stage at which it was left by his predecessor. </p> \r\n"
				+ "        <p> 40) It is expressly agreed to by the parties hereto that nothing contained in this clause or any contained in this Loan document shall limit the right of the Bank\r\n"
				+ "            to take any action or steps, or proceedings under the law, as may be applicable from time to time and to approach any tribunal, court or any other forum\r\n"
				+ "            of competent jurisdiction for recovery of the dues, interest, costs, or any other damages under this Loan document.</p>    \r\n"
				+ "        <br>\r\n"
				+ "        <br>\r\n"
				+ "            <p style=\"font-size: 10px;\"> I, ___"+aocpvLoanCreation.getCustomerName()+"____, W/o/D/o of____________________________, resident of _____________________________________________ , do hereby confirm </p>\r\n"
				+ "        <p style=\"font-size: 10px;\"> that I have understood the terms and conditions of Loan for ` _____________________ sanctioned to me and I convey my acceptance to the same. I authorize Suryoday</p>\r\n"
				+ "        <p style=\"font-size: 10px;\"> Small Finance Bank Ltd to disburse the loan amount into my bank account no. __"+aocpvLoanCreation.getLoanAccoutNumber()+"___ opened with _Suryoday Small Finance Bank Ltd_Bank</p>                 \r\n"
				+ "        <br>\r\n"
				+ "        <br>\r\n"
				+ "        <br>\r\n"
				+ "        <p> Signature/Thumb Impression of Borrower <span class=\"tab\" style=\"padding-left: 350px;\"> Signature/Thumb Impression of Guarantor </p>\r\n"
				+ "            <br>\r\n"
				+ "            <br>\r\n"
				+ "        <h3 style=\"padding-left: 230px; font-weight: bold;\"> DEMAND PROMISSORY NOTE</h3>   \r\n"
				+ "        <div class=\"box\" style=\"width:700px; height: 650px; border: 1px solid black;\">\r\n"
				+ "            <p style=\"text-align: center;\"><u>DEMAND PROMISSORY NOTE</u></p>\r\n"
				+ "            <p style=\"font-size: 10px;\">Date:</p>\r\n"
				+ "            <br>\r\n"
				+ "            <p style=\"font-size: 10px;\">On demand, I promise to pay Suryoday Small finance Bank Ltd or its assignee(s) a sum of ₹ _______ ( ₹________________________________________________) for\r\n"
				+ "                value received together with interest at ______% on reducing balance with monthly rests. </p>\r\n"
				+ "                <div class=\"id\" style=\"padding-left: 500px;\"> \r\n"
				+ "                    <div class=\"box2\" style=\"width: 150px; height: 100px; border: 1px solid black;\">\r\n"
				+ "                        <br>\r\n"
				+ "                        <p style=\"text-align: center; \">₹ 1</p>\r\n"
				+ "                        <p style=\"padding-left: 10px;\">Revenue Stamp</p>\r\n"
				+ "                    </div>\r\n"
				+ "                </div>\r\n"
				+ "            <p style=\"font-size: 10px;\">Borrower’s Name: _____________________________________________  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Signature/Thumb Impression of Borrower</p>\r\n"
				+ "            <br>\r\n"
				+ "            <p style=\"font-size: 10px;\">Guarantor Name: ______________________________________________  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Signature/Thumb Impression of Guarantor</p>    \r\n"
				+ "            <br>\r\n"
				+ "            <br>\r\n"
				+ "            <br>\r\n"
				+ "            <div class=\"border\" style=\"width: 100%; border: 1px solid black;\"></div>\r\n"
				+ "            <p style=\"font-weight: bold; text-align: center;\">Suryoday Small Finance Bank Ltd </p>\r\n"
				+ "            <p style=\"text-align: center;\">Registered Office: 1101, Sharda Terraces, Plot 65, Sector 11, CBD Belapur, Navi Mumbai-400614 | Tel 022-40435800 | Fax 022-40435813</p>\r\n"
				+ "            <p style=\"text-align: center;\">Company Identification Number U65923MH2008PTC261472</p>\r\n"
				+ "            <p style=\"text-align: center;\">Email: <a href=\"info@suryodaybank.com\" style=\"text-decoration: none; color: #00788a\">info@suryodaybank.com</a>| Website: <a href=\"www.suryodaybank.com\" style=\"text-decoration: none; color: #00788a\">www.suryodaybank.com</a>|</p>\r\n"
				+ "            <p style=\"font-weight: bold; text-align: center;\">Customer Care No. 1800 102 0210 (Toll Free)</p>\r\n"
				+ "        </div>    \r\n"
				+ "        </div>\r\n"
				+ "    </body>\r\n"
				+ "</html>      "));
		return htmlString.toString();
	}

}
