package com.suryoday.mhl.controller;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.servlet.http.HttpServletResponse;

import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.ClientAnchor;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.ss.usermodel.Drawing;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.Picture;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.util.IOUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/mhl")
public class ExcelController {

	Logger logger = LoggerFactory.getLogger(ExcelController.class);

	@RequestMapping(value = "/export/excel", method = RequestMethod.POST)
	public String exportToExcel(HttpServletResponse response) throws FileNotFoundException, IOException {
		response.setContentType("application/octet-stream");

		Workbook wb = new HSSFWorkbook();
		OutputStream os = new FileOutputStream("D:/PDF/cam.xlsx");
		Sheet sheet = wb.createSheet("CAM");
		InputStream inputStream = new FileInputStream(
				"C:\\Users\\Neosoft\\Documents\\UATPROJECT\\aocpvUat\\src\\main\\resources\\static\\logo.jpg");
		byte[] bytes = IOUtils.toByteArray(inputStream);
		int pictureIdx = wb.addPicture(bytes, Workbook.PICTURE_TYPE_PNG);
		inputStream.close();

		CreationHelper helper = wb.getCreationHelper();
		Drawing drawing = sheet.createDrawingPatriarch();
		ClientAnchor anchor = helper.createClientAnchor();
		Picture pict = drawing.createPicture(anchor, pictureIdx);
		anchor.setCol1(0);
		anchor.setRow1(0);
		pict.resize(4, 1);
		CellRangeAddress mergedRegion = new CellRangeAddress(0, 0, 6, 12);
		sheet.addMergedRegion(mergedRegion);

		Row row = sheet.createRow(0);
		Cell cell = row.createCell(6);
		row.setHeight((short) 1200);
		CellStyle style = wb.createCellStyle();
		cell.setCellValue("Micro HL (Loan Against Property)- CAM");

		Font font = wb.createFont();
		font.setFontName("Palatino Linotype");
		font.setFontHeightInPoints((short) 16);
		font.setBold(true);
		style.setFont(font);
		cell.setCellStyle(style);

		Row row2 = sheet.createRow(2);
		Cell cell2 = row2.createCell(0);
		cell2.setCellValue("       ");
		cell2 = row2.createCell(1);
		cell2.setCellValue("       ");
		sheet.addMergedRegion(new CellRangeAddress(2, 2, 1, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Lead generator Employee ID");
		sheet.addMergedRegion(new CellRangeAddress(2, 2, 3, 5));
		cell2 = row2.createCell(6);
		cell2.setCellValue("       ");
		sheet.addMergedRegion(new CellRangeAddress(2, 2, 6, 7));
		cell2 = row2.createCell(8);
		cell2.setCellValue("MHL Branch Name");
		sheet.addMergedRegion(new CellRangeAddress(2, 2, 8, 9));
		cell2 = row2.createCell(10);
		cell2.setCellValue("       ");
		sheet.addMergedRegion(new CellRangeAddress(2, 2, 10, 12));

		row2 = sheet.createRow(3);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Source");
		cell2 = row2.createCell(1);
		cell2.setCellValue("Inclusive Finance");
		sheet.addMergedRegion(new CellRangeAddress(3, 3, 1, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Lead closed Employee ID");
		sheet.addMergedRegion(new CellRangeAddress(3, 3, 3, 5));
		cell2 = row2.createCell(6);
		cell2.setCellValue("       ");
		sheet.addMergedRegion(new CellRangeAddress(3, 3, 6, 7));
		cell2 = row2.createCell(8);
		cell2.setCellValue("        ");
		sheet.addMergedRegion(new CellRangeAddress(3, 3, 8, 9));
		cell2 = row2.createCell(10);
		cell2.setCellValue("       ");
		sheet.addMergedRegion(new CellRangeAddress(3, 3, 10, 12));

		row2 = sheet.createRow(4);
		cell2 = row2.createCell(0);
		cell2.setCellValue("      ");
		cell2 = row2.createCell(1);
		cell2.setCellValue("         ");
		sheet.addMergedRegion(new CellRangeAddress(4, 4, 1, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Sourced By");
		sheet.addMergedRegion(new CellRangeAddress(4, 4, 3, 5));
		cell2 = row2.createCell(6);
		cell2.setCellValue("       ");
		sheet.addMergedRegion(new CellRangeAddress(4, 4, 6, 7));
		cell2 = row2.createCell(8);
		cell2.setCellValue("JLG Branch Name");
		sheet.addMergedRegion(new CellRangeAddress(4, 4, 8, 9));
		cell2 = row2.createCell(10);
		cell2.setCellValue("       ");
		sheet.addMergedRegion(new CellRangeAddress(4, 4, 10, 12));

		row2 = sheet.createRow(5);
		cell2 = row2.createCell(0);
		cell2.setCellValue("1) Details");
		sheet.addMergedRegion(new CellRangeAddress(5, 5, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Applicant");
		sheet.addMergedRegion(new CellRangeAddress(5, 5, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("Co-applicant 1");
		sheet.addMergedRegion(new CellRangeAddress(5, 5, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("Co-applicant 2");
		sheet.addMergedRegion(new CellRangeAddress(5, 5, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("Co-applicant 3");
		sheet.addMergedRegion(new CellRangeAddress(5, 5, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("Co-applicant 4");
		sheet.addMergedRegion(new CellRangeAddress(5, 5, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("Co-applicant 5");
		sheet.addMergedRegion(new CellRangeAddress(5, 5, 13, 14));

		row2 = sheet.createRow(6);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Name: ");
		sheet.addMergedRegion(new CellRangeAddress(6, 6, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("     ");
		sheet.addMergedRegion(new CellRangeAddress(6, 6, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(6, 6, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(6, 6, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(6, 6, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(6, 6, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(6, 6, 13, 14));

		row2 = sheet.createRow(7);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Age in years: ");
		sheet.addMergedRegion(new CellRangeAddress(7, 7, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("       ");
		sheet.addMergedRegion(new CellRangeAddress(7, 7, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(7, 7, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(7, 7, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(7, 7, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(7, 7, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(7, 7, 13, 14));

		row2 = sheet.createRow(8);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Gender (√): ");
		sheet.addMergedRegion(new CellRangeAddress(8, 8, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Female");
		sheet.addMergedRegion(new CellRangeAddress(8, 8, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("Female");
		sheet.addMergedRegion(new CellRangeAddress(8, 8, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(8, 8, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(8, 8, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(8, 8, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(8, 8, 13, 14));

		row2 = sheet.createRow(9);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Mobile Number: ");
		sheet.addMergedRegion(new CellRangeAddress(9, 9, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("       ");
		sheet.addMergedRegion(new CellRangeAddress(9, 9, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(9, 9, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(9, 9, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(9, 9, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(9, 9, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(9, 9, 13, 14));

		row2 = sheet.createRow(10);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Existing Customer with SSFB (Cust ID)");
		sheet.addMergedRegion(new CellRangeAddress(10, 10, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("       ");
		sheet.addMergedRegion(new CellRangeAddress(10, 10, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(10, 10, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(10, 10, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(10, 10, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(10, 10, 11, 12));
		cell2 = row2.createCell(13);
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(10, 10, 13, 14));

		row2 = sheet.createRow(11);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Relationship with applicant ");
		sheet.addMergedRegion(new CellRangeAddress(11, 11, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Son in law");
		sheet.addMergedRegion(new CellRangeAddress(11, 11, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("Son in law");
		sheet.addMergedRegion(new CellRangeAddress(11, 11, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(11, 11, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(11, 11, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(11, 11, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(11, 11, 13, 14));

		row2 = sheet.createRow(12);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Employment type ");
		sheet.addMergedRegion(new CellRangeAddress(12, 12, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("       ");
		sheet.addMergedRegion(new CellRangeAddress(12, 12, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(12, 12, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(12, 12, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(12, 12, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(12, 12, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(12, 12, 13, 14));

		row2 = sheet.createRow(13);
		cell2 = row2.createCell(0);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(13, 13, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Name working organisation:");
		sheet.addMergedRegion(new CellRangeAddress(13, 13, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(13, 13, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(13, 13, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(13, 13, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(13, 13, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(13, 13, 13, 14));

		row2 = sheet.createRow(14);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Salaried");
		sheet.addMergedRegion(new CellRangeAddress(14, 14, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Nature of work");
		sheet.addMergedRegion(new CellRangeAddress(14, 14, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(14, 14, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(14, 14, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(14, 14, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(14, 14, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(14, 14, 13, 14));

		row2 = sheet.createRow(15);
		cell2 = row2.createCell(0);
		cell2.setCellValue("    ");
		sheet.addMergedRegion(new CellRangeAddress(15, 15, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Experience in Years");
		sheet.addMergedRegion(new CellRangeAddress(15, 15, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("   1   ");
		sheet.addMergedRegion(new CellRangeAddress(15, 15, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(15, 15, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(15, 15, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(15, 15, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(15, 15, 13, 14));

		row2 = sheet.createRow(16);
		cell2 = row2.createCell(0);
		cell2.setCellValue("    ");
		sheet.addMergedRegion(new CellRangeAddress(16, 16, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Type");
		sheet.addMergedRegion(new CellRangeAddress(16, 16, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("Salary/ Wage without proof");
		sheet.addMergedRegion(new CellRangeAddress(16, 16, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(16, 16, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(16, 16, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(16, 16, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(16, 16, 13, 14));

		row2 = sheet.createRow(17);
		cell2 = row2.createCell(0);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(17, 17, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Nature of work or Business:");
		sheet.addMergedRegion(new CellRangeAddress(17, 17, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(17, 17, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(17, 17, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(17, 17, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(17, 17, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(17, 17, 13, 14));

		row2 = sheet.createRow(18);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Self Employed");
		sheet.addMergedRegion(new CellRangeAddress(18, 18, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Vintage of business in Years");
		sheet.addMergedRegion(new CellRangeAddress(18, 18, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("    10    ");
		sheet.addMergedRegion(new CellRangeAddress(18, 18, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(18, 18, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(18, 18, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(18, 18, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(18, 18, 13, 14));

		row2 = sheet.createRow(19);
		cell2 = row2.createCell(0);
		cell2.setCellValue("    ");
		sheet.addMergedRegion(new CellRangeAddress(19, 19, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Type of income");
		sheet.addMergedRegion(new CellRangeAddress(19, 19, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("With Manual bills");
		sheet.addMergedRegion(new CellRangeAddress(19, 19, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(19, 19, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(19, 19, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(19, 19, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(19, 19, 13, 14));

		row2 = sheet.createRow(20);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Monthly Income: (In Rs.) ");
		sheet.addMergedRegion(new CellRangeAddress(20, 20, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("20,000");
		sheet.addMergedRegion(new CellRangeAddress(20, 20, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(20, 20, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(20, 20, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(20, 20, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(20, 20, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(20, 20, 13, 14));

		row2 = sheet.createRow(21);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Income Proof");
		sheet.addMergedRegion(new CellRangeAddress(21, 21, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("     ");
		sheet.addMergedRegion(new CellRangeAddress(21, 21, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(21, 21, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(21, 21, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(21, 21, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(21, 21, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(21, 21, 13, 14));

		row2 = sheet.createRow(21);
		cell2 = row2.createCell(0);
		cell2.setCellValue(" Monthly Expenses: (In Rs.)");
		sheet.addMergedRegion(new CellRangeAddress(22, 22, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("   0  ");
		sheet.addMergedRegion(new CellRangeAddress(22, 22, 3, 14));

		row2 = sheet.createRow(23);
		cell2 = row2.createCell(0);
		cell2.setCellValue(" Assets: (In Rs.))");
		sheet.addMergedRegion(new CellRangeAddress(23, 23, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("   0  ");
		sheet.addMergedRegion(new CellRangeAddress(23, 23, 3, 14));

		row2 = sheet.createRow(24);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Liabilities: (In Rs.)");
		sheet.addMergedRegion(new CellRangeAddress(24, 24, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("   0  ");
		sheet.addMergedRegion(new CellRangeAddress(24, 24, 3, 14));

		row2 = sheet.createRow(25);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Current Residential Address");
		sheet.addMergedRegion(new CellRangeAddress(25, 25, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("     ");
		sheet.addMergedRegion(new CellRangeAddress(25, 25, 3, 14));

		row2 = sheet.createRow(26);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Current residence since (stability)");
		sheet.addMergedRegion(new CellRangeAddress(26, 26, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("     ");
		sheet.addMergedRegion(new CellRangeAddress(26, 26, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("Years");
		sheet.addMergedRegion(new CellRangeAddress(26, 26, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("Current residence status");
		sheet.addMergedRegion(new CellRangeAddress(26, 26, 7, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(26, 26, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(26, 26, 13, 14));

		row2 = sheet.createRow(27);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Residence address validated through");
		sheet.addMergedRegion(new CellRangeAddress(27, 27, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("     ");
		sheet.addMergedRegion(new CellRangeAddress(27, 27, 3, 14));

		row2 = sheet.createRow(28);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Distance of residence from Branch in KMs:");
		sheet.addMergedRegion(new CellRangeAddress(28, 28, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("     ");
		sheet.addMergedRegion(new CellRangeAddress(28, 28, 3, 14));

		row2 = sheet.createRow(29);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Family Details:");
		sheet.addMergedRegion(new CellRangeAddress(29, 29, 0, 14));

		row2 = sheet.createRow(34);
		cell2 = row2.createCell(0);
		cell2.setCellValue("PD Details on income assessment: ");
		sheet.addMergedRegion(new CellRangeAddress(34, 34, 0, 14));

		row2 = sheet.createRow(39);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Banking History:  ");
		sheet.addMergedRegion(new CellRangeAddress(39, 39, 0, 14));

		row2 = sheet.createRow(44);
		cell2 = row2.createCell(0);
		cell2.setCellValue("2) Sector, Subsector and PSL  Details:  ");
		sheet.addMergedRegion(new CellRangeAddress(44, 44, 0, 14));

		row2 = sheet.createRow(45);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Purpose");
		cell2 = row2.createCell(1);
		cell2.setCellValue("Loan Against Property");
		sheet.addMergedRegion(new CellRangeAddress(45, 45, 1, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Udyam Aadhar available");
		sheet.addMergedRegion(new CellRangeAddress(45, 45, 3, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("No");
		sheet.addMergedRegion(new CellRangeAddress(45, 45, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("Priority Sector (PSL)");
		sheet.addMergedRegion(new CellRangeAddress(45, 45, 9, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("No");
		sheet.addMergedRegion(new CellRangeAddress(45, 45, 13, 14));

		row2 = sheet.createRow(46);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Sector Code");
		sheet.addMergedRegion(new CellRangeAddress(46, 46, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Service");
		sheet.addMergedRegion(new CellRangeAddress(46, 46, 3, 14));

		row2 = sheet.createRow(47);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Subsectore Code");
		sheet.addMergedRegion(new CellRangeAddress(47, 47, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Carpenter");
		sheet.addMergedRegion(new CellRangeAddress(47, 47, 3, 14));

		row2 = sheet.createRow(48);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Occupation code");
		sheet.addMergedRegion(new CellRangeAddress(48, 48, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("         Mfg of Grain Mill Products");
		sheet.addMergedRegion(new CellRangeAddress(48, 48, 3, 14));

		row2 = sheet.createRow(49);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Nature of Borrowable A/c");
		sheet.addMergedRegion(new CellRangeAddress(49, 49, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("99 - All Others");
		sheet.addMergedRegion(new CellRangeAddress(49, 49, 3, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("Organisation Code");
		sheet.addMergedRegion(new CellRangeAddress(49, 49, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("        42      ");
		sheet.addMergedRegion(new CellRangeAddress(49, 49, 9, 14));

		row2 = sheet.createRow(50);
		cell2 = row2.createCell(0);
		cell2.setCellValue("3) CIBIL & Equifax Details: ");
		sheet.addMergedRegion(new CellRangeAddress(50, 50, 0, 14));

		row2 = sheet.createRow(51);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Credit Bureau");
		sheet.addMergedRegion(new CellRangeAddress(51, 51, 0, 1));
		cell2 = row2.createCell(2);
		cell2.setCellValue("Applicant");
		sheet.addMergedRegion(new CellRangeAddress(51, 51, 2, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("Co-applicant 1");
		sheet.addMergedRegion(new CellRangeAddress(51, 51, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("Co-applicant 2");
		sheet.addMergedRegion(new CellRangeAddress(51, 51, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("Co-applicant 3");
		sheet.addMergedRegion(new CellRangeAddress(51, 51, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("Co-applicant 4");
		sheet.addMergedRegion(new CellRangeAddress(51, 51, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("Co-applicant 5");
		sheet.addMergedRegion(new CellRangeAddress(51, 51, 13, 14));

		row2 = sheet.createRow(52);
		cell2 = row2.createCell(0);
		cell2.setCellValue("CIBIL");
		sheet.addMergedRegion(new CellRangeAddress(52, 52, 0, 1));
		cell2 = row2.createCell(2);
		cell2.setCellValue("196");
		sheet.addMergedRegion(new CellRangeAddress(52, 52, 2, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("    ");
		sheet.addMergedRegion(new CellRangeAddress(52, 52, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("   ");
		sheet.addMergedRegion(new CellRangeAddress(52, 52, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("   ");
		sheet.addMergedRegion(new CellRangeAddress(52, 52, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("   ");
		sheet.addMergedRegion(new CellRangeAddress(52, 52, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("      ");
		sheet.addMergedRegion(new CellRangeAddress(52, 52, 13, 14));

		row2 = sheet.createRow(53);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Equifax");
		sheet.addMergedRegion(new CellRangeAddress(53, 53, 0, 1));
		cell2 = row2.createCell(2);
		cell2.setCellValue("        ");
		sheet.addMergedRegion(new CellRangeAddress(53, 53, 2, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("         ");
		sheet.addMergedRegion(new CellRangeAddress(53, 53, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("       ");
		sheet.addMergedRegion(new CellRangeAddress(53, 53, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("        ");
		sheet.addMergedRegion(new CellRangeAddress(53, 53, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("         ");
		sheet.addMergedRegion(new CellRangeAddress(53, 53, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("         ");
		sheet.addMergedRegion(new CellRangeAddress(53, 53, 13, 14));

		row2 = sheet.createRow(55);
		cell2 = row2.createCell(0);
		cell2.setCellValue("                          Active Loans                 ");
		sheet.addMergedRegion(new CellRangeAddress(55, 55, 0, 14));

		row2 = sheet.createRow(56);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Name");
		cell2 = row2.createCell(1);
		cell2.setCellValue("Type of Loan");
		sheet.addMergedRegion(new CellRangeAddress(56, 56, 1, 3));
		cell2 = row2.createCell(4);
		cell2.setCellValue("Loan Amount");
		sheet.addMergedRegion(new CellRangeAddress(56, 56, 4, 5));
		cell2 = row2.createCell(6);
		cell2.setCellValue("Current O/S");
		sheet.addMergedRegion(new CellRangeAddress(56, 56, 6, 7));
		cell2 = row2.createCell(8);
		cell2.setCellValue("EMI amt");
		sheet.addMergedRegion(new CellRangeAddress(56, 56, 8, 9));
		cell2 = row2.createCell(10);
		cell2.setCellValue("SSFB Loan");
		sheet.addMergedRegion(new CellRangeAddress(56, 56, 10, 11));
		cell2 = row2.createCell(12);
		cell2.setCellValue("Remarks");
		sheet.addMergedRegion(new CellRangeAddress(56, 56, 12, 14));

		row2 = sheet.createRow(62);
		cell2 = row2.createCell(0);
		cell2.setCellValue("   Remarks on default loan, if any:     ");
		sheet.addMergedRegion(new CellRangeAddress(62, 62, 0, 14));

		row2 = sheet.createRow(66);
		cell2 = row2.createCell(0);
		cell2.setCellValue("   Recent Housing Loan & LAP Enquiries; If any    ");
		sheet.addMergedRegion(new CellRangeAddress(66, 66, 0, 14));

		row2 = sheet.createRow(67);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Name of the Company");
		sheet.addMergedRegion(new CellRangeAddress(67, 67, 0, 3));
		cell2 = row2.createCell(4);
		cell2.setCellValue("Date of Enquiry");
		sheet.addMergedRegion(new CellRangeAddress(67, 67, 4, 5));
		cell2 = row2.createCell(6);
		cell2.setCellValue("Enquiry Amount");
		sheet.addMergedRegion(new CellRangeAddress(67, 67, 6, 7));
		cell2 = row2.createCell(8);
		cell2.setCellValue("               Status              ");
		sheet.addMergedRegion(new CellRangeAddress(67, 67, 8, 14));

		row2 = sheet.createRow(69);
		cell2 = row2.createCell(0);
		cell2.setCellValue(" 4) Loan Details");
		sheet.addMergedRegion(new CellRangeAddress(69, 69, 0, 14));

		row2 = sheet.createRow(70);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Product");
		sheet.addMergedRegion(new CellRangeAddress(70, 70, 0, 3));
		cell2 = row2.createCell(4);
		cell2.setCellValue("           LAP");
		sheet.addMergedRegion(new CellRangeAddress(70, 70, 4, 14));

		row2 = sheet.createRow(71);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Business Purpose");
		sheet.addMergedRegion(new CellRangeAddress(71, 71, 0, 3));
		cell2 = row2.createCell(4);
		cell2.setCellValue("           Business Purpose");
		sheet.addMergedRegion(new CellRangeAddress(71, 71, 4, 14));

		row2 = sheet.createRow(72);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Loan Amount Required in Rs:");
		sheet.addMergedRegion(new CellRangeAddress(72, 72, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("200,000");
		sheet.addMergedRegion(new CellRangeAddress(72, 72, 3, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("Tenure in months:");
		sheet.addMergedRegion(new CellRangeAddress(72, 72, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("        120      ");
		sheet.addMergedRegion(new CellRangeAddress(72, 72, 9, 14));

		row2 = sheet.createRow(73);
		cell2 = row2.createCell(0);
		cell2.setCellValue("ROI %");
		sheet.addMergedRegion(new CellRangeAddress(73, 73, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("18.00%");
		sheet.addMergedRegion(new CellRangeAddress(73, 73, 3, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("EMI");
		sheet.addMergedRegion(new CellRangeAddress(73, 73, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("        3,604      ");
		sheet.addMergedRegion(new CellRangeAddress(73, 73, 9, 14));

		row2 = sheet.createRow(74);
		cell2 = row2.createCell(0);
		cell2.setCellValue("LTV (%)");
		cell2 = row2.createCell(1);
		cell2.setCellValue("LTV On Property Cost");
		sheet.addMergedRegion(new CellRangeAddress(74, 74, 1, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("65%");
		sheet.addMergedRegion(new CellRangeAddress(74, 74, 3, 5));
		cell2 = row2.createCell(6);
		cell2.setCellValue("FOIR (In %)");
		sheet.addMergedRegion(new CellRangeAddress(74, 74, 6, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("        15%     ");
		sheet.addMergedRegion(new CellRangeAddress(74, 74, 9, 14));

		row2 = sheet.createRow(75);
		cell2 = row2.createCell(0);
		cell2.setCellValue(" 5) Details of Property to be financed ");
		sheet.addMergedRegion(new CellRangeAddress(75, 75, 0, 14));

		row2 = sheet.createRow(76);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Type of Loan ");
		sheet.addMergedRegion(new CellRangeAddress(76, 76, 0, 3));
		cell2 = row2.createCell(4);
		cell2.setCellValue("           LAP- Residential         ");
		sheet.addMergedRegion(new CellRangeAddress(76, 76, 4, 14));

		row2 = sheet.createRow(77);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Type of Property ");
		sheet.addMergedRegion(new CellRangeAddress(77, 77, 0, 3));
		cell2 = row2.createCell(4);
		cell2.setCellValue("           Self-Occupied property            ");
		sheet.addMergedRegion(new CellRangeAddress(77, 77, 4, 14));

		row2 = sheet.createRow(78);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Name of Property Holder/s: ");
		sheet.addMergedRegion(new CellRangeAddress(78, 78, 0, 3));

		row2 = sheet.createRow(79);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Property Classification ");
		sheet.addMergedRegion(new CellRangeAddress(79, 79, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Grampanchayath");
		sheet.addMergedRegion(new CellRangeAddress(79, 79, 3, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("Taluka");
		sheet.addMergedRegion(new CellRangeAddress(79, 79, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("              ");
		sheet.addMergedRegion(new CellRangeAddress(79, 79, 9, 14));

		row2 = sheet.createRow(80);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Plot Area in sq ft:  ");
		sheet.addMergedRegion(new CellRangeAddress(80, 80, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("           ");
		sheet.addMergedRegion(new CellRangeAddress(80, 80, 3, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("Year of Purchase:");
		sheet.addMergedRegion(new CellRangeAddress(80, 80, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("              ");
		sheet.addMergedRegion(new CellRangeAddress(80, 80, 9, 14));

		row2 = sheet.createRow(81);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Built-up Area in Sq Ft: ");
		sheet.addMergedRegion(new CellRangeAddress(81, 81, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("           ");
		sheet.addMergedRegion(new CellRangeAddress(81, 81, 3, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("Current Market Value in Rs.");
		sheet.addMergedRegion(new CellRangeAddress(81, 81, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("     1300000         ");
		sheet.addMergedRegion(new CellRangeAddress(81, 81, 9, 14));

		row2 = sheet.createRow(82);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Distance from Current Residence: (In KMs) ");
		sheet.addMergedRegion(new CellRangeAddress(82, 82, 0, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("           ");
		sheet.addMergedRegion(new CellRangeAddress(82, 82, 3, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("Distance of property from branch");
		sheet.addMergedRegion(new CellRangeAddress(82, 82, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("              ");
		sheet.addMergedRegion(new CellRangeAddress(82, 82, 9, 14));

		row2 = sheet.createRow(83);
		cell2 = row2.createCell(0);
		cell2.setCellValue("6) Attachments (PDF) ");
		sheet.addMergedRegion(new CellRangeAddress(83, 83, 0, 3));

		row2 = sheet.createRow(84);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Property Photos ");
		cell2 = row2.createCell(1);
		cell2.setCellValue("Business Photos");
		sheet.addMergedRegion(new CellRangeAddress(84, 84, 1, 3));
		cell2 = row2.createCell(4);
		cell2.setCellValue("RCU Report");
		sheet.addMergedRegion(new CellRangeAddress(84, 84, 4, 5));
		cell2 = row2.createCell(6);
		cell2.setCellValue("Bank Statement");
		sheet.addMergedRegion(new CellRangeAddress(84, 84, 6, 7));
		cell2 = row2.createCell(8);
		cell2.setCellValue("CIBIL Reports");
		sheet.addMergedRegion(new CellRangeAddress(84, 84, 8, 9));
		cell2 = row2.createCell(10);
		cell2.setCellValue("Equifax Reports");
		sheet.addMergedRegion(new CellRangeAddress(84, 84, 10, 11));
		cell2 = row2.createCell(12);
		cell2.setCellValue("Any other documents, if any");
		sheet.addMergedRegion(new CellRangeAddress(84, 84, 12, 14));

//        row2 = sheet.createRow(85);
//        sheet.addMergedRegion(new CellRangeAddress(84,89,0,0)); 
//        row2 = sheet.createRow(86);
//        sheet.addMergedRegion(new CellRangeAddress(84,89,1,3)); 
//        row2 = sheet.createRow(87);
//        sheet.addMergedRegion(new CellRangeAddress(84,89,4,5)); 
//        row2 = sheet.createRow(88);
//        sheet.addMergedRegion(new CellRangeAddress(84,85,6,7)); 
//        row2 = sheet.createRow(89);
//        sheet.addMergedRegion(new CellRangeAddress(84,85,0,0)); 

		row2 = sheet.createRow(90);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Administrative Charge (Including GST) ");
		sheet.addMergedRegion(new CellRangeAddress(90, 90, 0, 3));
		cell2 = row2.createCell(4);
		cell2.setCellValue("                         Rs.5000                        ");
		sheet.addMergedRegion(new CellRangeAddress(90, 90, 4, 14));

		row2 = sheet.createRow(91);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Processing Fees (Including GST) ");
		sheet.addMergedRegion(new CellRangeAddress(91, 91, 0, 3));
		cell2 = row2.createCell(4);
		cell2.setCellValue("                         Rs.5000                        ");
		sheet.addMergedRegion(new CellRangeAddress(91, 91, 4, 14));

		row2 = sheet.createRow(92);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Deviation: ");
		sheet.addMergedRegion(new CellRangeAddress(92, 92, 0, 5));
		cell2 = row2.createCell(6);
		cell2.setCellValue("     Approving authority      ");
		sheet.addMergedRegion(new CellRangeAddress(92, 92, 6, 9));
		cell2 = row2.createCell(10);
		cell2.setCellValue("     Description of deviation      ");
		sheet.addMergedRegion(new CellRangeAddress(92, 92, 10, 14));

		row2 = sheet.createRow(93);
		cell2 = row2.createCell(0);
		cell2.setCellValue("           ");
		sheet.addMergedRegion(new CellRangeAddress(93, 93, 0, 5));
		cell2 = row2.createCell(6);
		cell2.setCellValue("#N/A       ");
		sheet.addMergedRegion(new CellRangeAddress(93, 93, 6, 9));
		cell2 = row2.createCell(10);
		cell2.setCellValue("        ");
		sheet.addMergedRegion(new CellRangeAddress(93, 93, 10, 14));

		row2 = sheet.createRow(94);
		cell2 = row2.createCell(0);
		cell2.setCellValue("           ");
		sheet.addMergedRegion(new CellRangeAddress(94, 94, 0, 5));
		cell2 = row2.createCell(6);
		cell2.setCellValue("#N/A       ");
		sheet.addMergedRegion(new CellRangeAddress(94, 94, 6, 9));
		cell2 = row2.createCell(10);
		cell2.setCellValue("        ");
		sheet.addMergedRegion(new CellRangeAddress(94, 94, 10, 14));

		row2 = sheet.createRow(95);
		cell2 = row2.createCell(0);
		cell2.setCellValue("           ");
		sheet.addMergedRegion(new CellRangeAddress(95, 95, 0, 5));
		cell2 = row2.createCell(6);
		cell2.setCellValue("#N/A       ");
		sheet.addMergedRegion(new CellRangeAddress(95, 95, 6, 9));
		cell2 = row2.createCell(10);
		cell2.setCellValue("        ");
		sheet.addMergedRegion(new CellRangeAddress(95, 95, 10, 14));

		row2 = sheet.createRow(96);
		cell2 = row2.createCell(0);
		cell2.setCellValue("           ");
		sheet.addMergedRegion(new CellRangeAddress(96, 96, 0, 5));
		cell2 = row2.createCell(6);
		cell2.setCellValue("#N/A       ");
		sheet.addMergedRegion(new CellRangeAddress(96, 96, 6, 9));
		cell2 = row2.createCell(10);
		cell2.setCellValue("        ");
		sheet.addMergedRegion(new CellRangeAddress(96, 96, 10, 14));

		row2 = sheet.createRow(97);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Mitigants:");
		sheet.addMergedRegion(new CellRangeAddress(97, 97, 0, 14));

		row2 = sheet.createRow(98);
		cell2 = row2.createCell(0);
		cell2.setCellValue("   1    ");
		cell2 = row2.createCell(1);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(98, 98, 1, 14));

		row2 = sheet.createRow(99);
		cell2 = row2.createCell(0);
		cell2.setCellValue("   2    ");
		cell2 = row2.createCell(1);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(99, 99, 1, 14));

		row2 = sheet.createRow(100);
		cell2 = row2.createCell(0);
		cell2.setCellValue("   3      ");
		cell2 = row2.createCell(1);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(100, 100, 1, 14));

		row2 = sheet.createRow(101);
		cell2 = row2.createCell(0);
		cell2.setCellValue("   4   ");
		cell2 = row2.createCell(1);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(101, 101, 1, 14));

		row2 = sheet.createRow(102);
		cell2 = row2.createCell(0);
		cell2.setCellValue("PSD Conditions:If any ");
		sheet.addMergedRegion(new CellRangeAddress(102, 102, 0, 14));

		row2 = sheet.createRow(103);
		cell2 = row2.createCell(0);
		cell2.setCellValue("   1    ");
		cell2 = row2.createCell(1);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(103, 103, 1, 14));

		row2 = sheet.createRow(104);
		cell2 = row2.createCell(0);
		cell2.setCellValue("   2    ");
		cell2 = row2.createCell(1);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(104, 104, 1, 14));

		row2 = sheet.createRow(105);
		cell2 = row2.createCell(0);
		cell2.setCellValue("   3      ");
		cell2 = row2.createCell(1);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(105, 105, 1, 14));

		row2 = sheet.createRow(106);
		cell2 = row2.createCell(0);
		cell2.setCellValue("7) Credit Manager Recommendation ");
		sheet.addMergedRegion(new CellRangeAddress(106, 106, 0, 14));

		row2 = sheet.createRow(107);
		cell2 = row2.createCell(0);
		cell2.setCellValue("          ");
		sheet.addMergedRegion(new CellRangeAddress(107, 110, 0, 14));

		row2 = sheet.createRow(111);
		cell2 = row2.createCell(0);
		cell2.setCellValue(
				"  I hereby certify that, I have personally visited the residence and business premise of the Applicant to conduct the credit evaluation of the Applicant . ");
		row2 = sheet.createRow(112);
		cell2 = row2.createCell(0);
		cell2.setCellValue(
				" The credit appraisal of the applicant is found to be satisfactory . My comments and observations are recorded above for further appraisal.");
		row2 = sheet.createRow(113);
		cell2 = row2.createCell(0);
		cell2.setCellValue("                    ");
		sheet.addMergedRegion(new CellRangeAddress(111, 113, 0, 14));

		row2 = sheet.createRow(114);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Recommender");
		sheet.addMergedRegion(new CellRangeAddress(114, 114, 0, 14));

		row2 = sheet.createRow(115);
		cell2 = row2.createCell(0);
		cell2.setCellValue("  Name");
		cell2 = row2.createCell(1);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(115, 115, 1, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Employee ID");
		sheet.addMergedRegion(new CellRangeAddress(115, 115, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(115, 115, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("Signature");
		sheet.addMergedRegion(new CellRangeAddress(115, 115, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(115, 115, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("Date");
		sheet.addMergedRegion(new CellRangeAddress(115, 115, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(115, 115, 13, 14));

		row2 = sheet.createRow(116);
		cell2 = row2.createCell(0);
		cell2.setCellValue("Approver");
		sheet.addMergedRegion(new CellRangeAddress(116, 116, 0, 14));

		row2 = sheet.createRow(117);
		cell2 = row2.createCell(0);
		cell2.setCellValue("  Name");
		cell2 = row2.createCell(1);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(117, 117, 1, 2));
		cell2 = row2.createCell(3);
		cell2.setCellValue("Employee ID");
		sheet.addMergedRegion(new CellRangeAddress(117, 117, 3, 4));
		cell2 = row2.createCell(5);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(117, 117, 5, 6));
		cell2 = row2.createCell(7);
		cell2.setCellValue("Signature");
		sheet.addMergedRegion(new CellRangeAddress(117, 117, 7, 8));
		cell2 = row2.createCell(9);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(117, 117, 9, 10));
		cell2 = row2.createCell(11);
		cell2.setCellValue("Date");
		sheet.addMergedRegion(new CellRangeAddress(117, 117, 11, 12));
		cell2 = row2.createCell(13);
		cell2.setCellValue("                ");
		sheet.addMergedRegion(new CellRangeAddress(117, 117, 13, 14));

		wb.write(os);
		return "Excel Downloaded Successfully";
	}

}
